### ISSUE TITLE
Prone to spurious calling of the handler

### ISSUE THREAD

**Issue by retep998** [Detegr/rust-ctrlc#1]
```Rust
            loop {
                let _ = CVAR.wait(MUTEX.lock().unwrap());
                user_handler();
            }
```
Waiting on a condition variable is prone to spurious wakeups. Therefore there should likely be some sort of check to ensure it wasn't a spurious wakeup.

**Comment by Detegr** [comment]
You're right, I had forgotten this quirk of condition variables.
I have a patch ready but waiting for #2 to be merged first to avoid conflicts.
