### ISSUE TITLE
Make it work inside `cargo run`

### ISSUE THREAD

**Issue by dns2utf8** [Detegr/rust-ctrlc#11]
Thank you for the crate.
It currently works on the university system (currently win10) with cmd and powershell, while I use my program directly.
When I start it with `cargo run` the handler will not execute. Can I enable that?

**Comment by Detegr** [comment]
Hi.
This is a known issue. Cargo overrides the ctrl-c management and unfortunately currently I'm unaware how to prevent that from happening.

**Comment by dns2utf8** [comment]
yes, I use a cmd script

**Comment by henninglive** [comment]
This has been [fixed](https://github.com/rust-lang/cargo/issues/2343) and has landed in stable. Cargo now proxy signals to child process.

**Comment by Detegr** [comment]
Hooray! :tada:
