### ISSUE TITLE
Compile error when building latest version

### ISSUE THREAD

**Issue by casey** [Detegr/rust-ctrlc#115]
A user of [just](https://github.com/casey/just) ran into a compilation error when doing `cargo install just@1.25.0`, see https://github.com/casey/just/issues/1944. Pinning ctrlc to version 3.1.1 seems to have fixed it. I don't know if this is a ctrlc issue, a just issue, or a conflict with another dependency, but I thought I'd create an issue here.

PS Thanks for the great crate!

**Comment by kornelski** [comment]
Same here:

```text
~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ctrlc-3.4.3/src/platform/unix/mod.rs:64:35
     |
64   |             let _ = unistd::close(pipe.1);
     |                     ------------- ^^^^^^ expected `i32`, found `OwnedFd`
     |                     |
     |                     arguments to this function are incorrect
```

**Comment by fdncred** [comment]
Same problem with nushell https://github.com/nushell/nushell/pull/12064#issuecomment-1987006057.

**Comment by kornelski** [comment]
@Detegr Could you yank the release?

**Comment by taiki-e** [comment]
I opened https://github.com/Detegr/rust-ctrlc/pull/116 to fix this, but it would still be desirable to yank the 3.4.3, even if the fix is released soon.
