### ISSUE TITLE
Ctrl+C seems not to be working on Mac OS

### ISSUE THREAD

**Issue by neutrinoks** [Detegr/rust-ctrlc#120]
Hello 👋 

Has using Ctrl+C been tested on a Mac? Code that works pretty fine on my Linux machine does not work on my Mac.

I tried different terminals, such as the official Terminal from Apple, iTerm2, and WezTerm. I also tried bash and zsh as shells.

Regards,
Michael

**Comment by Detegr** [comment]
Yes, it has been tested on a Mac and the CI builds are run on Mac target too. What is your issue?

**Comment by neutrinoks** [comment]
Nothing happens when pressing CTRL+C... will check for settings 👍🏻 thanks 🙏🏻

**Comment by neutrinoks** [comment]
I checked my settings again and even played around with key remappings, but it still doesn't work on my MacBook Pro with an M2 chip running macOS Sonoma 14.6.1.

**Comment by neutrinoks** [comment]
Ahh :bulb: I found out that my issue is related to something different on my code... All good here :+1:
