### ISSUE TITLE
Use sigaction without SA_RESTART instead?

### ISSUE THREAD

**Issue by lilydjwg** [Detegr/rust-ctrlc#16]
Currently it uses the `signal` function which translates to `sigaction` with the SA_RESTART flag. Most blocking syscalls aren't interrupted by it, e.g. reading from a file descriptor will continue to wait for data after the signal. Setting a `running` flag won't work unless that read returns and the process can check the `running` flag.

I encountered this when I was reading inotify events. <kbd>Ctrl-C</kbd> didn't stop it until the next event arrived. I'm on Arch Linux x86_64 if it matters.

The change won't be backwards compatible, so perhaps add another feature to opt in?

**Comment by henninglive** [comment]
Regardless of if we choose to expose `SA_RESTART`, we should be using `sigaction()` instead of `signal()`. `signal()` is essentially deprecated in favor of `sigaction()`.

**Comment by Detegr** [comment]
Do you have any idea how this works on Windows? I would like to keep this crate as cross-platform as possible and I kinda dislike platform-specific options. However, if this works differently on *nix and Windows nowadays I think it's reasonable to change the default value of `SA_RESTART` and maybe make it modifiable through `feature` (like we did with `SIGTERM`).

**Comment by lilydjwg** [comment]
It's already in the platform-specific code. I've created a pull request that works for me.

**Comment by henninglive** [comment]
Do not change the default, SA_RESTART should be enabled by default. Disabling it breaks all libraries that don’t handle EINTR correctly. If we expose SA_RESTART, we should do it through a feature flag.
There is nothing equivalent on windows, since the handler runs on its own thread, there is no need to interrupt system calls.

**Comment by Detegr** [comment]
Closed as stale.
