### ISSUE TITLE
Ignore Ctrl-C

### ISSUE THREAD

**Issue by henninglive** [Detegr/rust-ctrlc#25]
It would be nice if we could expose some way to ignore Ctrl-C signals without having to register an empty signal handler. Ignoring Ctrl-C is supported by the native API on both on Unix and Windows, so this shouldn’t be too hard.

There are some possible concerns related to child process inheritance. On Windows, the ignore ctrl-c status is inherited by child processes, which might be a problem. On Unix, the whole signal dispositions is inherited by child processes created via `fork(2)` on, but not by child processes created via `execve(2)`. Since `fork(2)` is almost never used in rust, we should be fine here.

**Comment by Detegr** [comment]
I think the most idiomatic way would be to change `set_handler` to take an `Option<F>` instead of `F`, that however would be backwards incompatible. If we want to preserve backwards compatibility, `fn set_empty_handler()` could do.

About the differences between operating systems, I would like to have the same behavior on all systems. I think if there's no way to make the behaviors between operating systems to be the same, it's better to leave the feature out.

**Comment by henninglive** [comment]
We are never going to archive 100% the same behavior, considering the underling OS mechanisms we abstracting over are completely different. I feel like allowing for this small difference is perfectly accessible.

On a Unix terminal, there is only one app in the foreground at a time, and only the foreground app will revive the `SIGINT`. If you want the signal distrusted to your children, you must do this manually. On windows the whole process group receives the `CTRL+C` event. Considering that when you block `CTRL+C` you most likely don’t want it to kill your children, I feel like inheriting the block status makes sense windows.

**Comment by Detegr** [comment]
Putting it that way it indeed sounds reasonable. I would like to change the `set_handler` function and release a new major version for this, what do you think?

**Comment by henninglive** [comment]
Yeah sure, if you don’t want to wait and maybe implement some of my other suggestions. We should mention the inherence behavior in the docs.

**Comment by Detegr** [comment]
Yeah sorry, I read through the issues starting from the oldest one and had not read the other proposals before commenting. Implementing the other suggestions seems to be the right thing to do here.
