### ISSUE TITLE
Should call user_handler() in interrupt handler?

### ISSUE THREAD

**Issue by rom1v** [Detegr/rust-ctrlc#31]
Looking at the [source code](https://github.com/Detegr/rust-ctrlc/blob/72f783efe3b9b5a9092008c53b0f69ac23d4d4ba/src/lib.rs#L292-L299), the user handler is called from a separate thread, not from the OS interrupt handler.

As a consequence, setting a flag in the user handler and reading it from elsewhere is inherently racy.

For instance, this cannot be written without race conditions:

```rust
static INTERRUPTED_BY_USER: AtomicBool = ATOMIC_BOOL_INIT;

fn main() {
    ctrlc::set_handler(move || {
        println!("Ctrl+C detected");
        INTERRUPTED_BY_USER.store(true, Ordering::Release));
    }
    // …
    if let Err(err) = some_io_call() {
        if err.kind() == io::ErrorKind::Interrupted {
            // problem: at this point, INTERRUPTED_BY_USER may not be set by the ctrlc handler yet
            if INTERRUPTED_BY_USER.load(Ordering::Acquire) {
                println!("User requested interruption");
                quit();
            } else {
                println!("Interrupted by some other signal, retry...");
                retry();
            }
        }   
    }
}
```

Do you see any problems with calling the user handler from the OS interrupt handler?

EDIT: probably related to https://github.com/Detegr/rust-ctrlc/issues/30 by the way.

**Comment by rom1v** [comment]
I found this [comment](https://github.com/Detegr/rust-ctrlc/pull/20#issuecomment-304006658):

> Running our handler in its own thread is unfortunate, but we cannot safely allow arbitrary rust code to run in the os_handler() since most operations are not async signal safe.

What if `ctrlc` expose an _unsafe_ API to register a user handler to be run directly in the `os_handler()`?

**Comment by henninglive** [comment]
The solution here is to provide a API with an custom safe abstraction over these atomic flag/counter type signal handlers, this can be implement without the extra thread. Here is my suggestion #27 for adding this, but I have not had the time implement anything yet.
