### ISSUE TITLE
eats CPU during readme example

### ISSUE THREAD

**Issue by inv2004** [Detegr/rust-ctrlc#33]
Found that readme example (possible while loop?) eats CPU intensively >30%.
Windows - 10

Are where any workaround? Because looks likes its the only library for windows.

**Comment by Detegr** [comment]
The example is very simple (even too simple, it seems), the high CPU load is caused by the spinloop that polls `running`. Try using [this version](https://github.com/Detegr/rust-ctrlc/blob/counter%2Bchannel/examples/readme_example.rs) for reduced CPU usage.
