### ISSUE TITLE
Make ctrlc::platform::block_ctrl_c() public?

### ISSUE THREAD

**Issue by nathan-osman** [Detegr/rust-ctrlc#47]
Is it possible to make `ctrlc::platform::block_ctrl_c()` public? I am currently using a `Condvar` to emulate the behavior of this function and being able to use it directly would greatly simplify things:

```rust
use std::sync::{Arc, Condvar, Mutex};

let pair = Arc::new((Mutex::new(false), Condvar::new()));
let copy = pair.clone();

ctrlc::set_handler(move || {
    let &(ref lock, ref cvar) = &*copy;
    let mut started = lock.lock().unwrap();
    *started = true;
    cvar.notify_one();
})
.expect("unable to set signal handler");

let &(ref lock, ref cvar) = &*pair;

let mut started = lock.lock().unwrap();
while !*started {
    started = cvar.wait(started).unwrap();
}
```

**Comment by Detegr** [comment]
That could be made public, but I'm just a few minor improvements away from implementing #27 and #28, which are going to make the current API obsolete. Basically the thing you're after could be implemented with `Channel` like I've demonstrated in the [channel example](https://github.com/Detegr/rust-ctrlc/blob/counter%2Bchannel_wip/examples/channel_example.rs) in my work-in-progress branch.

**Comment by nathan-osman** [comment]
Ah, okay. Your implementation makes much more sense then.
