### ISSUE TITLE
High CPU usage using provided example

### ISSUE THREAD

**Issue by madprops** [Detegr/rust-ctrlc#58]
```rust
// Detect ctrl+c 
// to exit the program
pub fn start_ctrlc()
{
    thread::spawn(move || 
    {
        let running = Arc::new(AtomicBool::new(true));
        let r = running.clone();

        ctrlc::set_handler(move || {
            r.store(false, Ordering::SeqCst);
        }).unwrap();

        while running.load(Ordering::SeqCst) {}
        exit();
    });
}
```

Using this my CPU usage stays at a constant 25%. Doesn't happen if I don't start that function.
If I'm supposed to do something to limit thread usage it should be documented.

**Comment by madprops** [comment]
Nvm I think this is due to mis-usage.

**Comment by Detegr** [comment]
The provided example is as simple as possible. Therefore it has a
busy-loop without a sleep inside. This is why you were getting 100% CPU
load.

While I like to keep the example as simple as possible, it might be
reasonable to add a sleep to prevent confusing people. Thank you for the
input.
