### ISSUE TITLE
Closure type taken by `set_handler()` should be `FnMut`

### ISSUE THREAD

**Issue by abonander** [Detegr/rust-ctrlc#59]
The reasoning for taking `Fn` and not `FnMut` is not documented and it's not clear from the implementation why the restriction is necessary as the handler is never called concurrently.

**Comment by Detegr** [comment]
I don't think there's any particular reason why it could not be `FnMut`. I can't remember the exact details but I would guess my reasoning has been that it does not **need** to be `FnMut` so I've used `Fn` instead. I agree that it could be changed to `FnMut` instead, as it is non-breaking change.

**Comment by SOF3** [comment]
It would also be great to accept `FnOnce` if it could be ensured that the handler function exits the process. I made a wrapper for this https://github.com/SOF3/ctrlc_fnonce, but I wonder if this could get into this repo.

**Comment by abonander** [comment]
This is doable with the `never_type` feature [which is hopefully due to be stabilized in 1.40](https://github.com/rust-lang/rust/issues/35121): 

```rust
fn set_handler_once<F: FnOnce() -> ! + Send + 'static>(f: F) {
    thread::spawn(move || {
        loop {
            // ... block waiting for Ctrl-C
            f();
        }
    });
}
```

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=504b7a7651f2c35cf88637cacd95efa1)

**Comment by abonander** [comment]
The `loop` is actually not necessary, either.

**Comment by Detegr** [comment]
I feel exiting the process within a signal handler is something you don't do very often in larger scale programs. I agree that it could be a nice addition while prototyping, but I would wait `never_type` to stabilize and put it behind a feature flag.

**Comment by SOF3** [comment]
Why should it return never, instead of returning `Termination`?

**Comment by abonander** [comment]
The way you worded it, I thought that you wanted to statically ensure that the closure itself exited the process; requiring it to return the never-type is the closest you can get.

Returning a status code to pass to `process::exit()` makes some sense, although `Termination` is also unstable, and it doesn't appear that there's been much discussion on stabilizing it.

I think an API that's more useful in general is being able to pass `FnOnce` as a one-off handler so you can do anything you want, including exiting the process.

**Comment by cheako** [comment]
It's perfectly reasonable to want to force the user to hit ctrl-c multiple times, so I don't think FnOnce should be mandatory.
