### ISSUE TITLE
ctrl-c not working when key remapped on linux

### ISSUE THREAD

**Issue by gilescope** [Detegr/rust-ctrlc#65]
My .xmodmap has Command and control switched as I'm on a mac but running Linux (nixos). Ctrl-c (for which I press Command-c) works for non-rust stuff but not for verco crate that uses this. I know this is pretty esoteric, but I figure it'd be a good corner case to nail down and as ctrl-c crate is so widely used it's good to make it rock solid.

.xmodmap contents:

```
clear control
clear mod4

keycode 105 =
keycode 206 =

keycode 133 = Control_L NoSymbol Control_L
keycode 134 = Control_R NoSymbol Control_R
keycode 37 = Super_L NoSymbol Super_L

add control = Control_L
add control = Control_R
add mod4 = Super_L
```

When I get a spare minute I'll try and create a failing test, but first step is to log it as an issue.

**Comment by gilescope** [comment]
Hmm, maybe it is something in verco - the readme_example works fine despite the key remapping...

**Comment by Detegr** [comment]
Thank you for reporting an issue. However, key remaps don't have anything to do with this crate. This just handles the signal that is generated by the operating system.
It seems like `verco` crate [does not do anything](https://github.com/matheuslessarodrigues/verco/blob/master/src/main.rs#L11) in the ctrlc handler, so this is an issue for that crate instead.
