### ISSUE TITLE
v3.1.5 ctrlc::set_handler() weird errors 

### ISSUE THREAD

**Issue by teknsl** [Detegr/rust-ctrlc#67]
```rs
ctrlc::set_handler(move || { })
```
from rust analyzer: ``Syntax Error: expected BANG``
from cargo / rustc: 
```
error: expected one of ! or ::, found (

 ctrlc::set_handler(move || { })
                   ^ expected one of ! or ::
````

in addition my editor(vsc) does not have any autocomplete at all on it, but it has the docs shown when you finish the function. this does look like a compiler issue or something else, but this is the only time i have gotten this

os: Windows 10  
rustc: 1.44.1  
ctrlc ver: 3.1.5

**Comment by Detegr** [comment]
Could you post the complete program that fails to compile? I think there's a syntax error in some earlier code, or this is some weird compiler bug indeed. Could not reproduce this with 1.44.1 on Linux though, so I'm not so sure about the compiler bug.

**Comment by teknsl** [comment]
this was very early on in a project so i barely have anything in the main file besides use and mod, even with everything commented out still getting the same error, tried with a blank project and that neither worked
