### ISSUE TITLE
Simpler example without busy loop but channels

### ISSUE THREAD

**Issue by Jikstra** [Detegr/rust-ctrlc#76]
```
use std::sync::mpsc::channel;
use ctrlc;

fn main() {
    let (interrupt_sender, interrupt_receiver) = channel();
    
    ctrlc::set_handler(move || {
        interrupt_sender.send(()).expect("Could not send signal on channel.")
    }).expect("Error setting Ctrl-C handler");
    
    println!("Waiting for Ctrl-C...");
    interrupt_receiver.recv().expect("Could not receive from channel.");
    println!("Got it! Exiting...");
}
```

I'm not a rust/threading expert but this is a solution I came accross which is probably helpful for others too? Not sure what are the downsides of this vs the provided example. But to me it feels cleaner/less code and more performant as it doesn't cause a busy loop.

**Comment by Detegr** [comment]
I think that'll work fine. I would rename `interrupt_sender` and `interrupt_receiver` for `tx` and `rx`, or something similar, because generally an interrupt has a different meaning than a signal. There's no downsides as far as I know, you're welcome to send a pull request if you'd like.

**Comment by Jikstra** [comment]
Perfect, will send a pr soon :)
