### ISSUE TITLE
Handling runs after the loop executes

### ISSUE THREAD

**Issue by KanseiKy** [Detegr/rust-ctrlc#79]
![image](https://user-images.githubusercontent.com/86419969/123447941-fac38000-d60c-11eb-9e60-d4884af052b4.png)
As you can see, the above image show ``$ $ Keyboard intterupt. Use `exit` to exit``
What I expect it to be is something like
```sh
$ *ctrl+c*
Keyboard intterupt. Use `exit` to exit`
$
```
But that didn't happened. It runs the next iteration from my `loop`. Basically
```
prompt
wait for user input
ctrl+c
prompt
SIGINT handling
wait for user input
```
It should be
```
prompt
wait for user input
ctrl+c
SIGINT handling
prompt
wait for user input
```
(`SIGINT handling` and 2nd `prompt` supposed to swap places)
I don't know if this is a bug or not but I can send more details if required

**Comment by Detegr** [comment]
Does this happen to you if you run `cargo run --example readme_example`?

**Comment by Detegr** [comment]
Closed as stale.
