### ISSUE TITLE
Migrate to `windows`/`-sys` crate

### ISSUE THREAD

**Issue by ok-nick** [Detegr/rust-ctrlc#85]
`winapi` is a community-maintained crate for windows bindings that has received only a single update in the last year. Microsoft has officially released their own set of bindings providing both a raw low-level crate, `windows-sys`, and a higherish-level crate (with some helper traits and etc), `windows`.
As the general Rust ecosystem is migrating to the new windows crates, `ctrlc` should follow. It would be preferable to use the `windows-sys` crate over the `windows` crate as it should cut down on any extra compilation times. Additionally, since the scale of this project is relatively small, I don't think it would benefit from any abstractions made by the `windows` crate.

**Comment by Detegr** [comment]
Thanks for the info. I agree this would be a good thing to do.

**Comment by Detegr** [comment]
Migration done in #92
